# Generated by Django 4.1.3 on 2026-02-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AquaticLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品種名稱')),
                ('category', models.CharField(choices=[('SHRIMP', '米蝦/螯蝦'), ('FISH', '觀賞魚'), ('PLANT', '水生植物'), ('OTHER', '其他')], default='SHRIMP', max_length=10, verbose_name='分類')),
                ('city', models.CharField(choices=[('KLU', '基隆市'), ('TP', '臺北市'), ('NTP', '新北市'), ('TY', '桃園市'), ('HCU', '新竹市'), ('HCH', '新竹縣'), ('ILN', '宜蘭縣'), ('MLI', '苗栗縣'), ('TC', '臺中市'), ('CHH', '彰化縣'), ('NTO', '南投縣'), ('YLN', '雲林縣'), ('CYI', '嘉義市'), ('CYH', '嘉義縣'), ('TN', '臺南市'), ('KH', '高雄市'), ('PTH', '屏東縣'), ('HUA', '花蓮縣'), ('TTT', '臺東縣'), ('PEH', '澎湖縣'), ('KMN', '金門縣'), ('LJN', '連江縣')], default='NTP', max_length=5, verbose_name='所在地點')),
                ('price', models.IntegerField(default=0, verbose_name='價格')),
                ('stock', models.IntegerField(default=0, verbose_name='庫存數量')),
                ('description', models.TextField(blank=True, verbose_name='詳細描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上架時間')),
            ],
        ),
    ]
