# Generated by Django 4.1.3 on 2026-02-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaticlife',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='aquatic_images/'),
        ),
    ]
