# Generated by Django 6.0.2 on 2026-02-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.JSONField(default=list, help_text='儲存區塊資料的清單'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_photos/'),
        ),
    ]
