# Generated by Django 6.0.2 on 2026-02-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
