# Generated by Django 6.0.2 on 2026-03-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0007_comment_likes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.JSONField(blank=True, default=list, help_text='儲存區塊資料的清單', null=True),
        ),
    ]
