# Generated by Django 6.0.2 on 2026-03-24 16:36

import aquatic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0008_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='folder_uuid',
            field=models.CharField(editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=aquatic.models.get_blog_upload_path),
        ),
    ]
