# Generated by Django 6.0.2 on 2026-03-27 06:08

import aquatic.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0011_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaticlife',
            name='folder_uuid',
            field=models.CharField(editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticlife',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=aquatic.models.get_aquatic_upload_path, verbose_name='商品封面圖'),
        ),
        migrations.CreateModel(
            name='AquaticImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=aquatic.models.get_aquatic_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='aquatic.aquaticlife')),
            ],
        ),
    ]
