# Generated by Django 6.0.2 on 2026-03-27 08:16

import aquatic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0012_aquaticlife_folder_uuid_alter_aquaticlife_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='folder_uuid',
            field=models.CharField(editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=aquatic.models.get_profile_upload_path, verbose_name='大頭貼'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=aquatic.models.get_profile_upload_path, verbose_name='個人頁背景'),
        ),
    ]
