# Generated by Django 6.0.2 on 2026-03-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0013_profile_folder_uuid_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaticlife',
            name='price_status',
            field=models.CharField(choices=[('NORMAL', '正常顯示價格'), ('NOT_FOR_SALE', '非賣品'), ('NEGOTIABLE', '面議')], default='NORMAL', max_length=20, verbose_name='價格狀態'),
        ),
    ]
