# Generated by Django 6.0.2 on 2026-03-28 16:21

import posixpath

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import aquatic.models.post_comment


def get_pet_upload_path(instance, filename):
    """
    歷史 migration 使用的上傳路徑。
    """
    token = instance.folder_uuid

    return posixpath.join(
        "profiles",
        token,
        "pets",
        "main.webp",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("aquatic", "0015_alter_aquaticlife_price_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="comment_count",
        ),
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="建立時間",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aquaticlife",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(verbose_name="留言內容"),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="comment_count",
            field=models.IntegerField(default=0, verbose_name="留言數"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=aquatic.models.post_comment.get_blog_upload_path,
                verbose_name="文章封面",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="like_count",
            field=models.IntegerField(default=0, verbose_name="點讚數"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=150, verbose_name="文章標題"),
        ),
        migrations.CreateModel(
            name="PetFish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folder_uuid",
                    models.CharField(editable=False, max_length=8, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="小魚名字")),
                (
                    "species",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="品種(選填)"
                    ),
                ),
                (
                    "main_photo",
                    models.ImageField(
                        upload_to=get_pet_upload_path,
                        verbose_name="展示美照",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="關於牠的故事")),
                (
                    "last_feeding_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最後餵食時間"
                    ),
                ),
                (
                    "feeding_interval_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="建議餵食間隔(小時)"
                    ),
                ),
                (
                    "feeding_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="累計被餵食次數"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_pets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShopNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="模板標題")),
                ("content", models.TextField(verbose_name="教學內容")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
