# Generated by Django 6.0.2 on 2026-03-31 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0016_remove_comment_comment_count_profile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaticlife',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aquatic_items', to=settings.AUTH_USER_MODEL, verbose_name='發布者'),
        ),
    ]
