# Generated by Django 6.0.2 on 2026-04-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0017_aquaticlife_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopnotice',
            name='title',
            field=models.CharField(max_length=200, verbose_name='模板標題'),
        ),
    ]
