# Generated by Django 6.0.2 on 2026-04-24 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0019_spectemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaticlife',
            name='adult_length',
            field=models.FloatField(blank=True, null=True, verbose_name='成魚體長(cm)'),
        ),
        migrations.AddField(
            model_name='aquaticlife',
            name='difficulty',
            field=models.IntegerField(default=1, verbose_name='養殖難易度'),
        ),
        migrations.AddField(
            model_name='aquaticlife',
            name='min_tank_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='建議缸徑(cm)'),
        ),
        migrations.AddField(
            model_name='aquaticlife',
            name='notice_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='aquatic.shopnotice', verbose_name='套用的購物須知'),
        ),
        migrations.AddField(
            model_name='aquaticlife',
            name='ph_max',
            field=models.FloatField(blank=True, null=True, verbose_name='最大pH值'),
        ),
        migrations.AddField(
            model_name='aquaticlife',
            name='ph_min',
            field=models.FloatField(blank=True, null=True, verbose_name='最小pH值'),
        ),
        migrations.AddField(
            model_name='aquaticlife',
            name='specs_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='其他詳細規格'),
        ),
        migrations.AddField(
            model_name='aquaticlife',
            name='temp_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='最大溫度'),
        ),
        migrations.AddField(
            model_name='aquaticlife',
            name='temp_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='最小溫度'),
        ),
        migrations.AlterField(
            model_name='spectemplate',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='範本數據'),
        ),
        migrations.AlterField(
            model_name='spectemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='規格範本名稱'),
        ),
    ]
