# Generated by Django 6.0.2 on 2026-05-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0020_aquaticlife_adult_length_aquaticlife_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquaticlife',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='aquaticlife',
            name='category',
            field=models.CharField(choices=[('FISH', '魚類'), ('SHRIMP', '蝦類'), ('PLANT', '水生植物'), ('SHELLFISH', '螺蚌類'), ('OTHER', '其他')], default='SHRIMP', max_length=10, verbose_name='產品種類'),
        ),
    ]
