# Generated by Django 6.0.2 on 2026-05-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0021_remove_aquaticlife_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquaticlife',
            name='min_tank_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='建議水量(L)'),
        ),
    ]
