# Generated by Django 6.0.2 on 2026-05-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0022_alter_aquaticlife_min_tank_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaticlife',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
