# Generated by Django 6.0.2 on 2026-05-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0023_aquaticlife_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_detail',
            field=models.CharField(blank=True, max_length=150, verbose_name='詳細地址'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city_region',
            field=models.CharField(blank=True, max_length=50, verbose_name='縣市行政區'),
        ),
        migrations.AlterField(
            model_name='aquaticlife',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否有效'),
        ),
    ]
