# Generated by Django 6.0.2 on 2026-05-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0025_alter_aquaticlife_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquaticlife',
            name='city',
            field=models.CharField(choices=[('NONE', '無資訊'), ('KLU', '基隆市'), ('TP', '臺北市'), ('NTP', '新北市'), ('TY', '桃園市'), ('HCU', '新竹市'), ('HCH', '新竹縣'), ('ILN', '宜蘭縣'), ('MLI', '苗栗縣'), ('TC', '臺中市'), ('CHH', '彰化縣'), ('NTO', '南投縣'), ('YLN', '雲林縣'), ('CYI', '嘉義市'), ('CYH', '嘉義縣'), ('TN', '臺南市'), ('KH', '高雄市'), ('PTH', '屏東縣'), ('HUA', '花蓮縣'), ('TTT', '臺東縣'), ('PEH', '澎湖縣'), ('KMN', '金門縣'), ('LJN', '連江縣')], default='NONE', max_length=50, verbose_name='所在地點'),
        ),
    ]
