# Generated by Django 6.0.6 on 2026-07-07 05:14

import aquatic.models.aquatic_life_img
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0026_alter_aquaticlife_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaticlife',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=aquatic.models.aquatic_life_img.get_aquatic_upload_path, verbose_name='商品影片(MP4/WebM)'),
        ),
        migrations.AlterField(
            model_name='aquaticlife',
            name='category',
            field=models.CharField(choices=[('FISH', '魚類'), ('SHRIMP', '蝦類'), ('PLANT', '水草類'), ('SHELLFISH', '螺蚌類'), ('OTHER', '其他')], default='SHRIMP', max_length=10, verbose_name='產品種類'),
        ),
        migrations.AlterField(
            model_name='aquaticlife',
            name='city',
            field=models.CharField(choices=[('NONE', '無資訊'), ('基隆市', '基隆市'), ('臺北市', '臺北市'), ('新北市', '新北市'), ('桃園市', '桃園市'), ('新竹市', '新竹市'), ('新竹縣', '新竹縣'), ('苗栗縣', '苗栗縣'), ('臺中市', '臺中市'), ('彰化縣', '彰化縣'), ('南投縣', '南投縣'), ('雲林縣', '雲林縣'), ('嘉義市', '嘉義市'), ('嘉義縣', '嘉義縣'), ('臺南市', '臺南市'), ('高雄市', '高雄市'), ('屏東縣', '屏東縣'), ('宜蘭縣', '宜蘭縣'), ('花蓮縣', '花蓮縣'), ('臺東縣', '臺東縣'), ('澎湖縣', '澎湖縣'), ('金門縣', '金門縣'), ('連江縣', '連江縣')], default='NONE', max_length=50, verbose_name='所在地點'),
        ),
    ]
