# Generated by Django 6.0.6 on 2026-07-11 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0027_aquaticlife_video_alter_aquaticlife_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_link',
            field=models.URLField(blank=True, verbose_name='聯絡連結'),
        ),
        migrations.AddField(
            model_name='profile',
            name='follower_count',
            field=models.PositiveIntegerField(default=0, verbose_name='追蹤總數'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_profiles', to=settings.AUTH_USER_MODEL, verbose_name='追蹤者名單'),
        ),
    ]
