# Generated by Django 6.0.6 on 2026-07-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0028_profile_contact_link_profile_follower_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquaticlife',
            name='price_status',
        ),
        migrations.AlterField(
            model_name='aquaticlife',
            name='category',
            field=models.CharField(choices=[('DOUYU', '鬥魚'), ('FISH', '觀賞魚'), ('SHRIMP', '蝦類'), ('PLANT', '水草類'), ('SHELLFISH', '螺蚌類'), ('OTHER', '其他')], default='SHRIMP', max_length=10, verbose_name='產品種類'),
        ),
        migrations.AlterField(
            model_name='aquaticlife',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否上架'),
        ),
    ]
