# Generated by Django 6.0.6 on 2026-07-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0029_remove_aquaticlife_price_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_price',
            field=models.BooleanField(default=False, verbose_name='對未追蹤者隱藏價格'),
        ),
    ]
