# Generated by Django 6.0.6 on 2026-07-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0030_profile_hide_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hide_price',
        ),
        migrations.AddField(
            model_name='profile',
            name='price_visibility',
            field=models.CharField(choices=[('PUBLIC', '公開顯示'), ('FOLLOWERS', '追蹤後顯示'), ('HIDDEN', '隱藏價格')], default='PUBLIC', max_length=20, verbose_name='價格顯示方式'),
        ),
        migrations.AlterField(
            model_name='aquaticlife',
            name='category',
            field=models.CharField(choices=[('DOUYU', '鬥魚'), ('FISH', '觀賞魚'), ('GOLDFISH', '金魚'), ('RATFISH', '鼠魚'), ('SHRIMP', '蝦類'), ('PLANT', '水草類'), ('SHELLFISH', '螺蚌類'), ('OTHER', '其他')], default='SHRIMP', max_length=10, verbose_name='產品種類'),
        ),
    ]
