# Generated by Django 6.0.6 on 2026-07-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0031_remove_profile_hide_price_profile_price_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaticlife',
            name='body_length',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='體長'),
        ),
        migrations.AddField(
            model_name='aquaticlife',
            name='temp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='適合溫度'),
        ),
    ]
