# Generated by Django 6.0.6 on 2026-07-16 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0034_remove_units_from_simple_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petfish',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='spectemplate',
            name='user',
        ),
        migrations.DeleteModel(
            name='AquaticImage',
        ),
        migrations.DeleteModel(
            name='PetFish',
        ),
        migrations.DeleteModel(
            name='SpecTemplate',
        ),
    ]
