# Generated by Django 6.0.6 on 2026-07-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatic', '0035_remove_petfish_owner_remove_spectemplate_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquaticlife',
            name='category',
            field=models.CharField(choices=[('DOUYU', '鬥魚'), ('GOLDFISH', '金魚'), ('RATFISH', '鼠魚'), ('SHRIMP', '蝦類'), ('PLANT', '水草類'), ('SHELLFISH', '螺蚌類'), ('OTHER', '其他')], default='SHRIMP', max_length=10, verbose_name='產品種類'),
        ),
    ]
